import { supabaseAdmin } from '../config/supabase.js';

/**
 * MENX Safe Test Fixture Cleanup Utility
 *
 * Scans the database for orphaned test records generated by automated test runs
 * (identifiable by millisecond epoch timestamps like -1788143460307).
 *
 * Usage:
 *   node src/scripts/cleanup_orphaned_test_fixtures.js             (Dry Run preview only)
 *   node src/scripts/cleanup_orphaned_test_fixtures.js --execute  (Executes safe cleanup)
 */

async function main() {
  const isExecute = process.argv.includes('--execute');

  console.log('================================================================');
  console.log(`MENX ORPHANED TEST FIXTURE CLEANUP ${isExecute ? '[EXECUTION MODE]' : '[DRY RUN MODE]'}`);
  console.log('================================================================\n');

  if (!isExecute) {
    console.log('NOTE: Running in DRY-RUN mode. No database records will be modified.');
    console.log('Pass "--execute" flag to apply deletions.\n');
  }

  // 1. Identify test categories
  const { data: allCategories } = await supabaseAdmin
    .from('categories')
    .select('id, name, slug, created_at');

  const testCategories = (allCategories || []).filter(c => 
    /-\d{10,}/.test(c.slug) || /-\d{10,}/.test(c.name) || c.name.startsWith('Apparel-')
  );

  // 2. Identify test products
  const { data: allProducts } = await supabaseAdmin
    .from('products')
    .select('id, title, slug, created_at');

  const testProducts = (allProducts || []).filter(p => 
    /-\d{10,}/.test(p.slug) || p.slug.startsWith('f4f-test-product-') || p.slug.startsWith('f4g-test-product-')
  );

  // 3. Identify test sizes
  const { data: allSizes } = await supabaseAdmin
    .from('sizes')
    .select('id, name, code');

  const testSizes = (allSizes || []).filter(s => 
    /-\d{10,}/.test(s.name) || (s.code && /-\d{10,}/.test(s.code))
  );

  // 4. Identify test colors
  const { data: allColors } = await supabaseAdmin
    .from('colors')
    .select('id, name');

  const testColors = (allColors || []).filter(c => 
    /-\d{10,}/.test(c.name)
  );

  console.log(`[SCAN RESULTS]`);
  console.log(`- Test Categories found: ${testCategories.length}`);
  testCategories.forEach(c => console.log(`    • [Category] ${c.name} (${c.slug}) [ID: ${c.id}]`));

  console.log(`- Test Products found: ${testProducts.length}`);
  testProducts.forEach(p => console.log(`    • [Product] ${p.title} (${p.slug}) [ID: ${p.id}]`));

  console.log(`- Test Sizes found: ${testSizes.length}`);
  testSizes.forEach(s => console.log(`    • [Size] ${s.name} [ID: ${s.id}]`));

  console.log(`- Test Colors found: ${testColors.length}`);
  testColors.forEach(c => console.log(`    • [Color] ${c.name} [ID: ${c.id}]`));

  if (testCategories.length === 0 && testProducts.length === 0 && testSizes.length === 0 && testColors.length === 0) {
    console.log('\nNo orphaned test records found. Database is clean!');
    process.exit(0);
  }

  if (!isExecute) {
    console.log('\n[DRY RUN COMPLETE] To delete these test records, run:');
    console.log('node src/scripts/cleanup_orphaned_test_fixtures.js --execute');
    process.exit(0);
  }

  console.log('\n[EXECUTING SAFE PURGE] Deleting orphaned test records in dependency order...');

  // Delete product relations
  const testProductIds = testProducts.map(p => p.id);
  if (testProductIds.length > 0) {
    // Variants
    const { data: variants } = await supabaseAdmin
      .from('product_variants')
      .select('id')
      .in('product_id', testProductIds);
    
    const variantIds = (variants || []).map(v => v.id);
    if (variantIds.length > 0) {
      await supabaseAdmin.from('inventory_items').delete().in('variant_id', variantIds);
      await supabaseAdmin.from('product_variants').delete().in('id', variantIds);
    }

    // Images
    await supabaseAdmin.from('product_images').delete().in('product_id', testProductIds);

    // Products
    await supabaseAdmin.from('products').delete().in('id', testProductIds);
    console.log(` ✅ Purged ${testProducts.length} test products and their variants/images.`);
  }

  // Delete subcategories of test categories
  const testCategoryIds = testCategories.map(c => c.id);
  if (testCategoryIds.length > 0) {
    await supabaseAdmin.from('subcategories').delete().in('category_id', testCategoryIds);
    await supabaseAdmin.from('categories').delete().in('id', testCategoryIds);
    console.log(` ✅ Purged ${testCategories.length} test categories.`);
  }

  // Delete test sizes & colors
  if (testSizes.length > 0) {
    await supabaseAdmin.from('sizes').delete().in('id', testSizes.map(s => s.id));
    console.log(` ✅ Purged ${testSizes.length} test sizes.`);
  }

  if (testColors.length > 0) {
    await supabaseAdmin.from('colors').delete().in('id', testColors.map(c => c.id));
    console.log(` ✅ Purged ${testColors.length} test colors.`);
  }

  console.log('\n[SUCCESS] All targeted orphaned test fixtures have been cleanly removed.');
}

main().catch(err => {
  console.error('[ERROR] Failed to complete test fixture cleanup:', err);
  process.exit(1);
});
