export const USER_ROLES = {
  CUSTOMER: 'CUSTOMER',
  STORE_STAFF: 'STORE_STAFF',
  INVENTORY_MANAGER: 'INVENTORY_MANAGER',
  ORDER_MANAGER: 'ORDER_MANAGER',
  STORE_MANAGER: 'STORE_MANAGER',
  SUPER_ADMIN: 'SUPER_ADMIN'
};

export const ROLE_HIERARCHY = {
  CUSTOMER: 1,
  STORE_STAFF: 2,
  INVENTORY_MANAGER: 3,
  ORDER_MANAGER: 3,
  STORE_MANAGER: 4,
  SUPER_ADMIN: 5
};

export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500
};
